// Miyuki Rocaille (round) seed beads — full official Miyuki color catalog
// generated from the Miyuki Rocaille Database reference file.
// Bead numbers are prefixed with "MR-" to keep them distinct from Delica "DB-" codes.
// Hex values are estimated from color descriptions and finish modifiers.
import { BeadColor } from './miyuki';

export const miyukiRoundColors: BeadColor[] = [
  { code: 'MR-1', name: 'Silver Lined Crystal', hex: '#e4ebeb', type: 'Silver-Lined' },
  { code: 'MR-2', name: 'Silver-Lined (S/L) Pale Topaz', hex: '#cba479', type: 'Silver-Lined' },
  { code: 'MR-3', name: 'Silver Lined Gold', hex: '#d0ae48', type: 'Silver-Lined' },
  { code: 'MR-5', name: 'Silver Lined Dark Topaz', hex: '#825f37', type: 'Silver-Lined' },
  { code: 'MR-6', name: 'Silver Lined Yellow', hex: '#ebc941', type: 'Silver-Lined' },
  { code: 'MR-8', name: 'Silver Lined Orange', hex: '#eb934f', type: 'Silver-Lined' },
  { code: 'MR-10', name: 'Silver Lined Cranberry', hex: '#a94057', type: 'Silver-Lined' },
  { code: 'MR-11D', name: 'Ruby Silver-Lined', hex: '#c93a55', type: 'Silver-Lined' },
  { code: 'MR-12', name: 'Silver Lined Smoky Amethyst', hex: '#9b7ea0', type: 'Silver-Lined' },
  { code: 'MR-13', name: 'Dk. Amethyst Silver-Lined', hex: '#714d82', type: 'Silver-Lined' },
  { code: 'MR-14', name: 'Silver Lined Chartreuse', hex: '#d0dd4f', type: 'Silver-Lined' },
  { code: 'MR-16', name: 'Silver Lined Green', hex: '#579b65', type: 'Silver-Lined' },
  { code: 'MR-18', name: 'Silver Lined Aqua', hex: '#63d0d0', type: 'Silver-Lined' },
  { code: 'MR-19', name: 'Blue Silver-Lined', hex: '#4f85d0', type: 'Silver-Lined' },
  { code: 'MR-20', name: 'Silver Lined Cobalt', hex: '#3e66d0', type: 'Silver-Lined' },
  { code: 'MR-21', name: 'Silver Lined Dark Silver', hex: '#949699', type: 'Silver-Lined' },
  { code: 'MR-23', name: 'Peach Silver-Lined', hex: '#f2d0b5', type: 'Silver-Lined' },
  { code: 'MR-24', name: 'Smoke Amethyst Silver-Lined', hex: '#9b7ea0', type: 'Silver-Lined' },
  { code: 'MR-25', name: 'Silver Lined Turquoise Blue', hex: '#4bc2d0', type: 'Silver-Lined' },
  { code: 'MR-26', name: 'Olive Green Silver-Lined', hex: '#818d48', type: 'Silver-Lined' },
  { code: 'MR-27', name: 'Silver Lined Forest Green', hex: '#3c6543', type: 'Silver-Lined' },
  { code: 'MR-29', name: 'Silver Lined Chocolate Brown', hex: '#745743', type: 'Silver-Lined' },
  { code: 'MR-37', name: 'Silk', hex: '#e8e2d6', type: 'Silk' },
  { code: 'MR-131', name: 'Transparent Crystal', hex: '#e0e8e8', type: 'Transparent' },
  { code: 'MR-131F', name: 'Transparent Matte Crystal', hex: '#e4e8e8', type: 'Matte' },
  { code: 'MR-131FR', name: 'Transparent Matte Rainbow White', hex: '#f6f6f4', type: 'Matte' },
  { code: 'MR-132', name: 'Light Topaz Yellow', hex: '#eed262', type: 'Other' },
  { code: 'MR-132F', name: 'Matte Transp. Lt. Topaz', hex: '#b79e82', type: 'Matte' },
  { code: 'MR-132FR', name: 'Transparent Matte Rainbow Khaki', hex: '#b3ac95', type: 'Matte' },
  { code: 'MR-132L', name: 'Transp. Pale Topaz', hex: '#c29562', type: 'Transparent' },
  { code: 'MR-133', name: 'Transp. Dk. Topaz', hex: '#6d4314', type: 'Transparent' },
  { code: 'MR-133F', name: 'Matte Transp. Dk. Topaz', hex: '#5b4226', type: 'Matte' },
  { code: 'MR-133FR', name: 'Matte Transp. Dk. Topaz AB', hex: '#735e46', type: 'Matte' },
  { code: 'MR-134', name: 'Root Beer Brown', hex: '#5a3018', type: 'Other' },
  { code: 'MR-134F', name: 'Matte Transp. Amber', hex: '#b18e56', type: 'Matte' },
  { code: 'MR-134FR', name: 'Matte Transp. Amber AB', hex: '#bc9e6f', type: 'Matte' },
  { code: 'MR-135', name: 'Coffee Brown', hex: '#5c3a1e', type: 'Other' },
  { code: 'MR-135F', name: 'Transparent Matte Chocolate Brown', hex: '#604e41', type: 'Matte' },
  { code: 'MR-135FR', name: 'Matte Transp. Lilac AB', hex: '#c8a2c8', type: 'Matte' },
  { code: 'MR-136', name: 'Daffodil', hex: '#f0d030', type: 'Other' },
  { code: 'MR-136F', name: 'Matte Transp. Yellow', hex: '#cdb761', type: 'Matte' },
  { code: 'MR-136FR', name: 'Matte Transp. Yellow AB', hex: '#d3c178', type: 'Matte' },
  { code: 'MR-138', name: 'Orange', hex: '#e88030', type: 'Other' },
  { code: 'MR-138F', name: 'Matte Transp. Orange', hex: '#c78f64', type: 'Matte' },
  { code: 'MR-138FR', name: 'Transparent Matte Rainbow Orange', hex: '#cf9f7a', type: 'Matte' },
  { code: 'MR-140', name: 'Tangerine Orange', hex: '#e86820', type: 'Other' },
  { code: 'MR-140F', name: 'Matte Transp. Red', hex: '#aa5d5d', type: 'Matte' },
  { code: 'MR-140FR', name: 'Matte Transp. Red AB', hex: '#b77474', type: 'Matte' },
  { code: 'MR-141D', name: 'Transp. Ruby', hex: '#c01838', type: 'Transparent' },
  { code: 'MR-142', name: 'Light Amethyst Purple', hex: '#ad7ec2', type: 'Other' },
  { code: 'MR-142F', name: 'Matte Transp. Lilac', hex: '#c8a2c8', type: 'Matte' },
  { code: 'MR-143', name: 'Transparent Light Daffodil Green', hex: '#f4de6e', type: 'Transparent' },
  { code: 'MR-143F', name: 'Matte Transp. Peridot', hex: '#a8be70', type: 'Matte' },
  { code: 'MR-144', name: 'Transp. Dk. Peridot', hex: '#6d8729', type: 'Transparent' },
  { code: 'MR-144F', name: 'Matte Transp. Dk. Peridot', hex: '#67773e', type: 'Matte' },
  { code: 'MR-146', name: 'Green', hex: '#3a8a4a', type: 'Other' },
  { code: 'MR-146F', name: 'Matte Transp. Green', hex: '#588361', type: 'Matte' },
  { code: 'MR-148', name: 'Light Blue', hex: '#6e9ad8', type: 'Other' },
  { code: 'MR-148D', name: 'Transp. Dk. Aqua', hex: '#2e8282', type: 'Transparent' },
  { code: 'MR-148F', name: 'Matte Transp. Aqua', hex: '#78bdbd', type: 'Matte' },
  { code: 'MR-148FR', name: 'Matte Transp. Aqua AB', hex: '#8cc7c7', type: 'Matte' },
  { code: 'MR-149', name: 'Sapphire Blue', hex: '#1c4cc8', type: 'Other' },
  { code: 'MR-149F', name: 'Matte Transp. Capri Blue', hex: '#74b1b1', type: 'Matte' },
  { code: 'MR-149FR', name: 'Matte Transp. Capri Blue AB', hex: '#89bcbc', type: 'Matte' },
  { code: 'MR-150', name: 'Transp. Blue', hex: '#3070c8', type: 'Transparent' },
  { code: 'MR-150F', name: 'Matte Transp. Blue', hex: '#5d81b0', type: 'Matte' },
  { code: 'MR-150FR', name: 'Matte Transp. Blue AB', hex: '#7693bb', type: 'Matte' },
  { code: 'MR-151', name: 'Transparent Royal Blue (Cobalt)', hex: '#1c3cc8', type: 'Transparent' },
  { code: 'MR-151F', name: 'Matte Transp. Cobalt', hex: '#4c66a9', type: 'Matte' },
  { code: 'MR-151FR', name: 'Matte Transp. Cobalt AB', hex: '#667cb6', type: 'Matte' },
  { code: 'MR-152', name: 'Transp. Grey', hex: '#8a8a8a', type: 'Transparent' },
  { code: 'MR-152F', name: 'Transparent Matte Light Grey', hex: '#b5b5b5', type: 'Matte' },
  { code: 'MR-152FR', name: 'Matte Transp. Grey AB', hex: '#a5a5a5', type: 'Matte' },
  { code: 'MR-153', name: 'Transp. Dk. Amethyst', hex: '#592e6d', type: 'Transparent' },
  { code: 'MR-153F', name: 'Matte Transp. Dk. Amethyst', hex: '#553c61', type: 'Matte' },
  { code: 'MR-153FR', name: 'Matte Transp. Wine AB', hex: '#7d575e', type: 'Matte' },
  { code: 'MR-155', name: 'Transparent Peach', hex: '#f0c8a8', type: 'Transparent' },
  { code: 'MR-155F', name: 'Matte Transp. Peach', hex: '#e4cebc', type: 'Matte' },
  { code: 'MR-155FR', name: 'Matte Transp. Peach AB', hex: '#e7d4c6', type: 'Matte' },
  { code: 'MR-156', name: 'Emerald Green', hex: '#1c8a3a', type: 'Other' },
  { code: 'MR-156F', name: 'Matte Transp. Dk. Green', hex: '#2d4c34', type: 'Matte' },
  { code: 'MR-156FR', name: 'Matte Transp. Dk. Green AB', hex: '#4c6652', type: 'Matte' },
  { code: 'MR-157', name: 'Transp. Smoke Amethyst', hex: '#8a6890', type: 'Transparent' },
  { code: 'MR-158', name: 'Transp. Olive Green', hex: '#6b7a28', type: 'Transparent' },
  { code: 'MR-158F', name: 'Transparent Matte Olive', hex: '#737b4e', type: 'Matte' },
  { code: 'MR-158FR', name: 'Matte Transp. Olive Green AB', hex: '#888e68', type: 'Matte' },
  { code: 'MR-160', name: 'Transparent Crystal Luster', hex: '#e0e8e8', type: 'Transparent' },
  { code: 'MR-162', name: 'Transparent Light Topaz Luster', hex: '#c29562', type: 'Transparent' },
  { code: 'MR-166', name: 'Transparent Light Siam Luster', hex: '#d86873', type: 'Transparent' },
  { code: 'MR-175', name: 'Transp. Blue Luster', hex: '#3070c8', type: 'Transparent' },
  { code: 'MR-177', name: 'Transparent Cobalt AB', hex: '#3e66d0', type: 'Transparent' },
  { code: 'MR-178', name: 'Transparent Gray Luster', hex: '#8a8a8a', type: 'Transparent' },
  { code: 'MR-179', name: 'Transparent Green AB', hex: '#579b65', type: 'Transparent' },
  { code: 'MR-187', name: 'Opaque Metallic Copper Plated', hex: '#b8683a', type: 'Galvanized' },
  { code: 'MR-188', name: 'Opaque Nickel Plated Metallic Golden Olive Iris', hex: '#d4af37', type: 'Galvanized' },
  { code: 'MR-190', name: 'Opaque Metallic Nickel Plated', hex: '#c8c8c8', type: 'Galvanized' },
  { code: 'MR-190F', name: 'Opaque Metallic Nickel Plated Matte', hex: '#c8c8c8', type: 'Matte Metallic' },
  { code: 'MR-191', name: 'Opaque Metallic 24Kt Gold Plated', hex: '#d4a020', type: 'Galvanized' },
  { code: 'MR-191F', name: 'Opaque 24Kt Gold Plated Matte', hex: '#d4a020', type: 'Matte' },
  { code: 'MR-191L', name: '24Kt Mid. Gold-Plated', hex: '#d4a020', type: 'Galvanized' },
  { code: 'MR-193', name: 'Opaque Metallic 24Kt Light Gold Plated', hex: '#d4a020', type: 'Galvanized' },
  { code: 'MR-193F', name: 'Opaque 24Kt Light Gold-Plated Matte', hex: '#d4a020', type: 'Matte' },
  { code: 'MR-194', name: 'Opaque Metallic Palladium Plated', hex: '#ced0dd', type: 'Galvanized' },
  { code: 'MR-194F', name: 'Palladium Plated Matte', hex: '#b8b8c0', type: 'Matte' },
  { code: 'MR-195', name: 'Transparent 24Kt Gold Lined Crystal', hex: '#fff2e8', type: 'Transparent' },
  { code: 'MR-196', name: 'Transparent 24Kt Gold Lined Opal', hex: '#d5bab0', type: 'Transparent' },
  { code: 'MR-197', name: 'Transparent Copper Lined Crystal', hex: '#efd0b9', type: 'Transparent' },
  { code: 'MR-198', name: 'Transparent Copper Lined Opal', hex: '#bf9e8c', type: 'Transparent' },
  { code: 'MR-249', name: 'Transparent Gray AB', hex: '#9b9b9b', type: 'Transparent' },
  { code: 'MR-250', name: 'Transparent Crystal AB', hex: '#e4ebeb', type: 'Transparent' },
  { code: 'MR-251', name: 'Transparent Light Topaz AB', hex: '#cba479', type: 'Transparent' },
  { code: 'MR-251L', name: 'Transp. Pale Topaz AB', hex: '#cba479', type: 'Transparent' },
  { code: 'MR-252', name: 'Transparent Yellow AB', hex: '#ebc941', type: 'Transparent' },
  { code: 'MR-253', name: 'Transparent Orange AB', hex: '#eb934f', type: 'Transparent' },
  { code: 'MR-254', name: 'Transparent Light Siam AB', hex: '#dd7e88', type: 'Transparent' },
  { code: 'MR-256', name: 'Transparent Smoky Amethyst AB', hex: '#9b7ea0', type: 'Transparent' },
  { code: 'MR-257', name: 'Transparent Topaz AB', hex: '#b57e41', type: 'Transparent' },
  { code: 'MR-258', name: 'Transparent Chartreuse AB', hex: '#d0dd4f', type: 'Transparent' },
  { code: 'MR-259', name: 'Transp. Dk. Peridot AB', hex: '#829949', type: 'Transparent' },
  { code: 'MR-260', name: 'Transparent Light Sapphire AB', hex: '#7793dd', type: 'Transparent' },
  { code: 'MR-261', name: 'Transp. Blue AB', hex: '#4f85d0', type: 'Transparent' },
  { code: 'MR-263', name: 'Transparent Color Lined Seafoam AB', hex: '#93d7c9', type: 'Transparent' },
  { code: 'MR-264', name: 'Transparent Color Lined Raspberry AB', hex: '#c93e6a', type: 'Transparent' },
  { code: 'MR-265', name: 'Transparent Color Lined Pale Pink AB', hex: '#f5c0d4', type: 'Transparent' },
  { code: 'MR-266', name: 'Transparent Color Lined Pink AB', hex: '#f2a7c2', type: 'Transparent' },
  { code: 'MR-272', name: 'Transparent Color Lined Medium Pink AB', hex: '#f2a7c2', type: 'Transparent' },
  { code: 'MR-273', name: 'Transparent Color Lined Pale Yellow AB', hex: '#f0d879', type: 'Transparent' },
  { code: 'MR-274', name: 'Transparent Color Lined Amethyst AB', hex: '#9b63b5', type: 'Transparent' },
  { code: 'MR-275', name: 'Transparent Color Lined Dark Peach AB', hex: '#aa9482', type: 'Transparent' },
  { code: 'MR-277', name: 'Transparent Color Lined Lime AB', hex: '#9dd05c', type: 'Transparent' },
  { code: 'MR-278', name: 'Transparent Color Lined Aqua AB', hex: '#63d0d0', type: 'Transparent' },
  { code: 'MR-279', name: 'Transparent Color Lined Marine Blue AB', hex: '#4f85b5', type: 'Transparent' },
  { code: 'MR-281', name: 'Transparent Color Lined Pale Peach AB', hex: '#f5ddcb', type: 'Transparent' },
  { code: 'MR-283', name: 'Transparent Color Lined Noir AB', hex: '#2a2a2a', type: 'Transparent' },
  { code: 'MR-284', name: 'Transparent Color Lined White AB', hex: '#f6f6f2', type: 'Transparent' },
  { code: 'MR-288', name: 'Transp. Olive Green AB', hex: '#818d48', type: 'Transparent' },
  { code: 'MR-289', name: 'Transparent Emerald AB', hex: '#3e9b57', type: 'Transparent' },
  { code: 'MR-291', name: 'Transparent Aquamarine AB', hex: '#c6ece9', type: 'Transparent' },
  { code: 'MR-292', name: 'Transp. Peach AB', hex: '#f2d0b5', type: 'Transparent' },
  { code: 'MR-293', name: 'Transp. Smoke Amethyst AB', hex: '#9b7ea0', type: 'Transparent' },
  { code: 'MR-294', name: 'Transp. Dk. Amethyst AB', hex: '#714d82', type: 'Transparent' },
  { code: 'MR-301', name: 'Transparent Dark Topaz Gold Luster AB', hex: '#825f37', type: 'Transparent' },
  { code: 'MR-302', name: 'Transparent Claret Gold Luster AB', hex: '#d0ae48', type: 'Transparent' },
  { code: 'MR-310', name: 'Transparent Peach Topaz Gold Luster', hex: '#f0c8a8', type: 'Transparent' },
  { code: 'MR-315', name: 'Transparent Garnet Gold Luster AB', hex: '#d0ae48', type: 'Transparent' },
  { code: 'MR-320', name: 'Transp. Smoke Amethyst Luster', hex: '#8a6890', type: 'Transparent' },
  { code: 'MR-321D', name: 'Transp. Dk. Aqua Luster', hex: '#2e8282', type: 'Transparent' },
  { code: 'MR-324D', name: 'Transp. Ruby Luster', hex: '#c01838', type: 'Transparent' },
  { code: 'MR-330', name: 'Transp. Peach Luster', hex: '#f0c8a8', type: 'Transparent' },
  { code: 'MR-339', name: 'Transparent Blue Color Lined Aqua AB', hex: '#63d0d0', type: 'Transparent' },
  { code: 'MR-342', name: 'Transparent Cranberry Color Lined Light Topaz AB', hex: '#c27989', type: 'Transparent' },
  { code: 'MR-343', name: 'Transparent Blue Color Lined Topaz AB', hex: '#b57e41', type: 'Transparent' },
  { code: 'MR-347', name: 'Transparent Aqua Color Lined Midnight Blue Luster AB', hex: '#63d0d0', type: 'Transparent' },
  { code: 'MR-353', name: 'Transparent Cobalt Color Lined Sapphire AB', hex: '#3e66d0', type: 'Transparent' },
  { code: 'MR-357', name: 'Transparent Root Beer Color Lined Topaz AB', hex: '#b57e41', type: 'Transparent' },
  { code: 'MR-363', name: 'Transparent Color Lined Light Cranberry AB', hex: '#c27989', type: 'Transparent' },
  { code: 'MR-367', name: 'Transparent Crystal Color Lined Garnet Luster AB', hex: '#e4ebeb', type: 'Transparent' },
  { code: 'MR-395', name: 'Transp. Olive Green Luster', hex: '#6b7a28', type: 'Transparent' },
  { code: 'MR-401', name: 'Opaque Black', hex: '#1a1a1a', type: 'Opaque' },
  { code: 'MR-401-F', name: 'Opaque Black Matte', hex: '#303030', type: 'Matte' },
  { code: 'MR-401FR', name: 'Matte Black AB', hex: '#4f4f4f', type: 'Matte' },
  { code: 'MR-402', name: 'Opaque White', hex: '#f5f5f0', type: 'Opaque' },
  { code: 'MR-402F', name: 'Opaque Whilte Frost', hex: '#f0f0f0', type: 'Matte' },
  { code: 'MR-402FR', name: 'Opaque White Matte', hex: '#f5f5f2', type: 'Matte' },
  { code: 'MR-404', name: 'Opaque Yellow', hex: '#e8c020', type: 'Opaque' },
  { code: 'MR-404D', name: 'Opaque Canary', hex: '#ffef00', type: 'Opaque' },
  { code: 'MR-404F', name: 'Matte Opaque Yellow', hex: '#cdb761', type: 'Matte' },
  { code: 'MR-405', name: 'Opaque Lt. Orange', hex: '#eea66e', type: 'Opaque' },
  { code: 'MR-405F', name: 'Matte Opaque Lt. Orange', hex: '#d7b092', type: 'Matte' },
  { code: 'MR-405FR', name: 'Matte Opaque Lt. Orange AB', hex: '#dcbba1', type: 'Matte' },
  { code: 'MR-406', name: 'Opaque Orange', hex: '#e88030', type: 'Opaque' },
  { code: 'MR-406F', name: 'Matte Opaque Orange', hex: '#c78f64', type: 'Matte' },
  { code: 'MR-406FR', name: 'Matte Opaque Orange AB', hex: '#cf9f7a', type: 'Matte' },
  { code: 'MR-407', name: 'Opaque Coral', hex: '#e07060', type: 'Opaque' },
  { code: 'MR-407F', name: 'Opaque Matte Red', hex: '#aa5d5d', type: 'Matte' },
  { code: 'MR-407FR', name: 'Matte Opaque Coral AB', hex: '#cd9a93', type: 'Matte' },
  { code: 'MR-408', name: 'Opaque Dark Cranberry Red', hex: '#641425', type: 'Opaque' },
  { code: 'MR-408D', name: 'Dark Opaque Red', hex: '#822424', type: 'Opaque' },
  { code: 'MR-408F', name: 'Matte Opaque Red', hex: '#aa5d5d', type: 'Matte' },
  { code: 'MR-408FR', name: 'Matte Orange Red AB', hex: '#cf9f7a', type: 'Matte' },
  { code: 'MR-409', name: 'Opaque Dark Chocolate Brown', hex: '#3b2516', type: 'Opaque' },
  { code: 'MR-409F', name: 'Matte Opaque Dk. Brown', hex: '#3b2c1f', type: 'Matte' },
  { code: 'MR-409FR', name: 'Opaque Matte Rainbow Purple', hex: '#9477a6', type: 'Matte' },
  { code: 'MR-410', name: 'Opaque Lilac', hex: '#c8a0d8', type: 'Opaque' },
  { code: 'MR-410F', name: 'Matte Opaque Lilac', hex: '#aa89aa', type: 'Matte' },
  { code: 'MR-410FR', name: 'Opaque Matte Rainbow Light Lavender', hex: '#d7cce2', type: 'Matte' },
  { code: 'MR-411F', name: 'Matte Opaque Green', hex: '#588361', type: 'Matte' },
  { code: 'MR-411FR', name: 'Matte Opaque Green AB', hex: '#709578', type: 'Matte' },
  { code: 'MR-412', name: 'Opaque Turquoise', hex: '#2cb8c8', type: 'Opaque' },
  { code: 'MR-412F', name: 'Matte Opaque Turquoise', hex: '#64afb8', type: 'Matte' },
  { code: 'MR-412FR', name: 'Opaque Matte Rainbow Turquoise Blue', hex: '#7abbc2', type: 'Matte' },
  { code: 'MR-412L', name: 'Opaque Lt. Turquoise', hex: '#6bcdd8', type: 'Opaque' },
  { code: 'MR-413', name: 'Opaque Lt. Blue', hex: '#6e9ad8', type: 'Opaque' },
  { code: 'MR-413F', name: 'Matte Opaque Lt. Blue', hex: '#8ea5c7', type: 'Matte' },
  { code: 'MR-413FR', name: 'Opaque Matte Rainbow Robins Egg Blue', hex: '#7693bb', type: 'Matte' },
  { code: 'MR-414', name: 'Opaque Dark Blue', hex: '#1f4882', type: 'Opaque' },
  { code: 'MR-414F', name: 'Opaque Matte Cobalt Blue', hex: '#4c66a9', type: 'Matte' },
  { code: 'MR-414FR', name: 'Matte Opaque Cobalt AB', hex: '#667cb6', type: 'Matte' },
  { code: 'MR-416', name: 'Opaque Lime', hex: '#8cc840', type: 'Opaque' },
  { code: 'MR-416F', name: 'Matte Opaque Lime', hex: '#94b56c', type: 'Matte' },
  { code: 'MR-416FR', name: 'Matte Opaque Lime AB', hex: '#a5c081', type: 'Matte' },
  { code: 'MR-417F', name: 'Matte Opaque Lt. Lapis', hex: '#2257a0', type: 'Matte' },
  { code: 'MR-417FR', name: 'Opaque Matte Cyan Blue AB', hex: '#7693bb', type: 'Matte' },
  { code: 'MR-419', name: 'Opaque Currant', hex: '#8b1a3a', type: 'Opaque' },
  { code: 'MR-419F', name: 'Matte Opaque Chocolate', hex: '#34211d', type: 'Matte' },
  { code: 'MR-420', name: 'Opaque Pearl White Luster', hex: '#f5f5f0', type: 'Opaque' },
  { code: 'MR-422D', name: 'Opaque Dk. Yellow Luster', hex: '#967c14', type: 'Opaque' },
  { code: 'MR-423', name: 'Opaque Lt. Orange Luster', hex: '#eea66e', type: 'Opaque' },
  { code: 'MR-425', name: 'Opaque Dk. Red Luster', hex: '#822424', type: 'Opaque' },
  { code: 'MR-432', name: 'Opaque Lt. Lapis Luster', hex: '#2867bd', type: 'Opaque' },
  { code: 'MR-440', name: 'Opaque Ivory Luster', hex: '#ece2c6', type: 'Opaque' },
  { code: 'MR-441', name: 'Ivory Luster', hex: '#ece2c6', type: 'Other' },
  { code: 'MR-442', name: 'Opaque Dk. Ivory Luster', hex: '#999280', type: 'Opaque' },
  { code: 'MR-443', name: 'Opaque Gray Luster', hex: '#8a8a8a', type: 'Opaque' },
  { code: 'MR-445', name: 'Opaque Chocolate Luster', hex: '#3e2723', type: 'Opaque' },
  { code: 'MR-448', name: 'Opaque Olive Green Luster', hex: '#6b7a28', type: 'Opaque' },
  { code: 'MR-451', name: 'Opaque Gunmetal', hex: '#2a2a2e', type: 'Opaque' },
  { code: 'MR-452', name: 'Blue Iris', hex: '#2870e5', type: 'Metallic' },
  { code: 'MR-453', name: 'Opaque Metallic Green Iris', hex: '#318a55', type: 'Opaque' },
  { code: 'MR-454', name: 'Opaque Metallic Purple Iris', hex: '#6738b8', type: 'Opaque' },
  { code: 'MR-455', name: 'Opaque Metallic Black Iris', hex: '#161a1d', type: 'Opaque' },
  { code: 'MR-456', name: 'Opaque Metallic Gunmetal Iris', hex: '#313a4b', type: 'Opaque' },
  { code: 'MR-457', name: 'Opaque Metallic Bronze', hex: '#8a6228', type: 'Opaque' },
  { code: 'MR-457L', name: 'Opaque Metallic Light Bronze', hex: '#ad9168', type: 'Opaque' },
  { code: 'MR-458', name: 'Opaque Metallic Brown Iris', hex: '#5a4428', type: 'Opaque' },
  { code: 'MR-459', name: 'Opaque Metallic Olive', hex: '#6b7a28', type: 'Opaque' },
  { code: 'MR-460', name: 'Opaque Metallic Dark Raspberry', hex: '#7c1234', type: 'Opaque' },
  { code: 'MR-462', name: 'Opaque Metallic Gold Iris', hex: '#aaa02e', type: 'Opaque' },
  { code: 'MR-468', name: 'Opaque Metallic Dark Green Iris', hex: '#1f5937', type: 'Opaque' },
  { code: 'MR-470', name: 'Transparent White Opal AB', hex: '#f6f6f2', type: 'Transparent' },
  { code: 'MR-471', name: 'Opaque Pearl White Luster AB', hex: '#f6f6f2', type: 'Opaque' },
  { code: 'MR-472', name: 'Opaque Yellow AB', hex: '#ebc941', type: 'Opaque' },
  { code: 'MR-472D', name: 'Opaque Canary AB', hex: '#ffef00', type: 'Opaque' },
  { code: 'MR-473', name: 'Opaque Lt. Orange AB', hex: '#f0b383', type: 'Opaque' },
  { code: 'MR-474', name: 'Opaque Orange AB', hex: '#eb934f', type: 'Opaque' },
  { code: 'MR-475', name: 'Opaque Light Siam AB', hex: '#dd7e88', type: 'Opaque' },
  { code: 'MR-476', name: 'Opaque Dark Red AB', hex: '#944444', type: 'Opaque' },
  { code: 'MR-478', name: 'Opaque Mauve AB', hex: '#a9809b', type: 'Opaque' },
  { code: 'MR-479', name: 'Opaque Chartreuse AB', hex: '#d0dd4f', type: 'Opaque' },
  { code: 'MR-480', name: 'Opaque Green AB', hex: '#579b65', type: 'Opaque' },
  { code: 'MR-481', name: 'Opaque Turquoise AB', hex: '#4bc2d0', type: 'Opaque' },
  { code: 'MR-482', name: 'Opaque Light Blue AB', hex: '#83a9dd', type: 'Opaque' },
  { code: 'MR-483', name: 'Opaque Periwinkle AB', hex: '#ccccff', type: 'Opaque' },
  { code: 'MR-484', name: 'Opaque Cobalt Blue AB', hex: '#3e66d0', type: 'Opaque' },
  { code: 'MR-485', name: 'Opaque Lt. Turquoise AB', hex: '#81d4dd', type: 'Opaque' },
  { code: 'MR-487', name: 'Opaque Cream AB', hex: '#f2e9d8', type: 'Opaque' },
  { code: 'MR-488', name: 'Opaque Dk. Ivory AB', hex: '#f0eed8', type: 'Opaque' },
  { code: 'MR-491', name: 'Light Opaque Ivory', hex: '#f1ead7', type: 'Opaque' },
  { code: 'MR-492', name: 'Opaque Ivory', hex: '#ece2c6', type: 'Opaque' },
  { code: 'MR-492F', name: 'Matte Opaque Ivory', hex: '#e7e2d2', type: 'Matte' },
  { code: 'MR-492FR', name: 'Opaque Matte Rainbow Eggshell', hex: '#f0ead6', type: 'Matte' },
  { code: 'MR-493', name: 'Opaque Dk. Ivory', hex: '#999280', type: 'Opaque' },
  { code: 'MR-493F', name: 'Matte Opaque Lt. Ivory', hex: '#edeae0', type: 'Matte' },
  { code: 'MR-494', name: 'Opaque Agate Blue', hex: '#3070c8', type: 'Opaque' },
  { code: 'MR-494F', name: 'Matte Opaque Ice Blue', hex: '#5d81b0', type: 'Matte' },
  { code: 'MR-498', name: 'Opaque Gray', hex: '#8a8a8a', type: 'Opaque' },
  { code: 'MR-498F', name: 'Opaque Matte Ghost Grey', hex: '#959595', type: 'Matte' },
  { code: 'MR-499', name: 'Opaque Grey', hex: '#8a8a8a', type: 'Opaque' },
  { code: 'MR-499F', name: 'Opaque Matte Steel Grey', hex: '#86868a', type: 'Matte' },
  { code: 'MR-500', name: 'Opaque Cocoa', hex: '#5c3a22', type: 'Opaque' },
  { code: 'MR-501', name: 'Opaque Avocado', hex: '#568235', type: 'Opaque' },
  { code: 'MR-501F', name: 'Matte Opaque Olive Green', hex: '#737b4e', type: 'Matte' },
  { code: 'MR-501FR', name: 'Matte Opaque Olive Green AB', hex: '#888e68', type: 'Matte' },
  { code: 'MR-511', name: 'Ceylon Pearl White Luster', hex: '#f5f5f0', type: 'Ceylon' },
  { code: 'MR-514', name: 'Ceylon Pale Yellow Luster', hex: '#eed262', type: 'Ceylon' },
  { code: 'MR-516', name: 'Ceylon Light Daffodil Luster', hex: '#f4de6e', type: 'Ceylon' },
  { code: 'MR-517', name: 'Ceylon Pink Luster', hex: '#f098b8', type: 'Ceylon' },
  { code: 'MR-518', name: 'Ceylon Bubblegum Pink Luster', hex: '#f098b8', type: 'Ceylon' },
  { code: 'MR-520', name: 'Ceylon Mint Green Luster', hex: '#3a8a4a', type: 'Ceylon' },
  { code: 'MR-522', name: 'Ceylon Light Aqua Luster', hex: '#7ed8d8', type: 'Ceylon' },
  { code: 'MR-524', name: 'Ceylon Sky-Blue Luster', hex: '#3070c8', type: 'Ceylon' },
  { code: 'MR-534', name: 'Ceylon Light Orchid Luster', hex: '#d8a0e3', type: 'Ceylon' },
  { code: 'MR-535', name: 'Ceylon Watermelon Luster', hex: '#e84858', type: 'Ceylon' },
  { code: 'MR-536', name: 'Ceylon Aqua Green Luster', hex: '#3a8a4a', type: 'Ceylon' },
  { code: 'MR-539', name: 'Ceylon Salmon Luster', hex: '#e89080', type: 'Ceylon' },
  { code: 'MR-544', name: 'Ceylon Cotton Candy Luster', hex: '#ffbcd9', type: 'Ceylon' },
  { code: 'MR-545', name: 'Ceylon Blue Luster', hex: '#3070c8', type: 'Ceylon' },
  { code: 'MR-550', name: 'Transparent White Opal', hex: '#f5f5f0', type: 'Transparent' },
  { code: 'MR-551', name: 'Transparent Gilt Lined Opal', hex: '#fafafa', type: 'Transparent' },
  { code: 'MR-553', name: 'Silver-Lined Opal Peach', hex: '#f2d0b5', type: 'Silver-Lined' },
  { code: 'MR-574', name: 'Silver-Lined Dyed Opal Light Purple', hex: '#af88c6', type: 'Silver-Lined' },
  { code: 'MR-593', name: 'Opaque Beige Glazed Luster', hex: '#cebfa0', type: 'Opaque' },
  { code: 'MR-594', name: 'Opaque Cream Glazed Luster', hex: '#f1e8d6', type: 'Opaque' },
  { code: 'MR-595', name: 'Opaque Light Beige Glazed Luster', hex: '#dcd2bc', type: 'Opaque' },
  { code: 'MR-597', name: 'Opaque Tan Gold Luster', hex: '#c8a028', type: 'Opaque' },
  { code: 'MR-599', name: 'Opaque Antique Rose Glazed Luster', hex: '#cd5a85', type: 'Opaque' },
  { code: 'MR-600', name: 'Opaque Alabaster Glazed Luster', hex: '#e8e0d8', type: 'Opaque' },
  { code: 'MR-650', name: 'Silver Lined Taupe Alabaster Dyed', hex: '#9a8b7a', type: 'Silver-Lined' },
  { code: 'MR-691', name: 'Transparent Gilt Lined Opal AB', hex: '#fafafa', type: 'Transparent' },
  { code: 'MR-953', name: 'Transparent 24Kt Gold Lined Aqua', hex: '#63d2c8', type: 'Transparent' },
  { code: 'MR-955', name: 'Transparent 24Kt Gold Lined Light Gray', hex: '#d2b7ad', type: 'Transparent' },
  { code: 'MR-957', name: 'Transparent 24Kt Gold Lined Lilac', hex: '#f0aad8', type: 'Transparent' },
  { code: 'MR-961', name: 'Bright Sterling Silver Plated', hex: '#c8ccd0', type: 'Other' },
  { code: 'MR-961F', name: 'Silver Plated Frost', hex: '#ced1d2', type: 'Matte' },
  { code: 'MR-971', name: 'Transparent Copper Lined Light Topaz', hex: '#d1864e', type: 'Transparent' },
  { code: 'MR-972', name: 'Transparent Copper Lined Olive', hex: '#7a6d20', type: 'Transparent' },
  { code: 'MR-973', name: 'Transparent Copper Lined Cobalt', hex: '#2b44a0', type: 'Transparent' },
  { code: 'MR-974', name: 'Transparent Copper Lined Bronze', hex: '#995820', type: 'Transparent' },
  { code: 'MR-1051', name: 'Galvanized Sterling Silver Plated', hex: '#cdd1d3', type: 'Galvanized' },
  { code: 'MR-1053', name: 'Galvanized Yellow Gold', hex: '#dbbf4b', type: 'Galvanized' },
  { code: 'MR-1055', name: 'Galvanized Light Gold', hex: '#c0a44d', type: 'Galvanized' },
  { code: 'MR-1072L', name: 'Galvanized Champagne', hex: '#f7e7c4', type: 'Galvanized' },
  { code: 'MR-1081', name: 'Galvanized Lilac', hex: '#cbaed7', type: 'Galvanized' },
  { code: 'MR-1105', name: 'Transparent Color Lined Silver Luster', hex: '#d0d3d7', type: 'Transparent' },
  { code: 'MR-1119', name: 'Luminous Neon Yellow', hex: '#eccc4c', type: 'Luminous' },
  { code: 'MR-1301', name: 'Light Yellow', hex: '#eed262', type: 'Other' },
  { code: 'MR-1302', name: 'Light Peach', hex: '#f4d8c2', type: 'Other' },
  { code: 'MR-1304', name: 'Creme De Mint Green', hex: '#3a8a4a', type: 'Other' },
  { code: 'MR-1308', name: 'Dark Rose Pink', hex: '#822e4e', type: 'Other' },
  { code: 'MR-1310', name: 'Hot Pink', hex: '#f098b8', type: 'Other' },
  { code: 'MR-1312', name: 'Raspberry Red', hex: '#c01c50', type: 'Other' },
  { code: 'MR-1315', name: 'Violet Purple', hex: '#7a38a0', type: 'Other' },
  { code: 'MR-1363', name: 'Opaque Salmon Pink', hex: '#e89080', type: 'Opaque' },
  { code: 'MR-1371', name: 'Opaque Rose', hex: '#c84878', type: 'Opaque' },
  { code: 'MR-1419', name: 'Silver-Lined Red', hex: '#d05555', type: 'Silver-Lined' },
  { code: 'MR-1420', name: 'Silver-Lined Transparent Dark Red', hex: '#944444', type: 'Silver-Lined' },
  { code: 'MR-1421', name: 'Silver-Lined Dark Topaz Brown', hex: '#604b38', type: 'Silver-Lined' },
  { code: 'MR-1424', name: 'Silver-Lined (S/L) Lt. Topaz Dyed', hex: '#cba479', type: 'Silver-Lined' },
  { code: 'MR-1425', name: 'Silver-Lined (S/L) Grey Dyed', hex: '#9b9b9b', type: 'Silver-Lined' },
  { code: 'MR-1426', name: 'Silver-Lined Transparent Dark Purple', hex: '#69447e', type: 'Silver-Lined' },
  { code: 'MR-1427', name: 'Silver-Lined (S/L) Cobalt Dyed', hex: '#3e66d0', type: 'Silver-Lined' },
  { code: 'MR-1428', name: 'Silver-Lined (S/L) Purple Dyed', hex: '#8d55ae', type: 'Silver-Lined' },
  { code: 'MR-1429', name: 'Silver-Lined (S/L) Orange Dyed', hex: '#eb934f', type: 'Silver-Lined' },
  { code: 'MR-1434', name: 'Silver-Lined Transparent Dark Burnt Orange', hex: '#a56c40', type: 'Silver-Lined' },
  { code: 'MR-1464', name: 'Opaque Red Dyed', hex: '#c83838', type: 'Opaque' },
  { code: 'MR-1609', name: 'Matte Transp. Red Dyed', hex: '#aa5d5d', type: 'Matte' },
  { code: 'MR-1622', name: 'Matte Dark Fuchsia Pink', hex: '#8f6c79', type: 'Matte' },
  { code: 'MR-1639', name: 'Semi-Matte S/L Red Dyed', hex: '#aa5d5d', type: 'Matte' },
  { code: 'MR-1643', name: 'Silver-Lined Dyed Semi-Frosted Light Aqua Blue', hex: '#aed7d7', type: 'Matte' },
  { code: 'MR-1654', name: 'Semi-Matte S/L Aqua Dyed', hex: '#78bdbd', type: 'Matte' },
  { code: 'MR-1657', name: 'Semi-Matte Silver Lined Gray Dyed', hex: '#a4a4a4', type: 'Matte' },
  { code: 'MR-1674', name: 'Matte Opaque Red Dyed', hex: '#aa5d5d', type: 'Matte' },
  { code: 'MR-1684', name: 'Matte Opaque Orange Dyed', hex: '#c78f64', type: 'Matte' },
  { code: 'MR-1820', name: 'Transparent Topaz Color Lined Cranberry Luster AB', hex: '#a94057', type: 'Transparent' },
  { code: 'MR-1827', name: 'Transparent Aqua Color Lined Purple Luster', hex: '#7a38a0', type: 'Transparent' },
  { code: 'MR-1828', name: 'Transparent Aqua Color Lined Blue Luster', hex: '#48c8c8', type: 'Transparent' },
  { code: 'MR-1865', name: 'Opaque Smoke Gray Gold Luster AB', hex: '#d4af37', type: 'Opaque' },
  { code: 'MR-1866', name: 'Opaque Ash Gray Gold Luster', hex: '#d4af37', type: 'Opaque' },
  { code: 'MR-1867', name: 'Opaque Dark Orchid Gold Luster', hex: '#824e8c', type: 'Opaque' },
  { code: 'MR-1880', name: 'Transparent Blue Glazed Luster', hex: '#447ecd', type: 'Transparent' },
  { code: 'MR-1881', name: 'Transparent Silver Gray Gold Luster', hex: '#e2ce8c', type: 'Transparent' },
  { code: 'MR-1882', name: 'Transparent Dark Topaz Gold Luster', hex: '#6d4314', type: 'Transparent' },
  { code: 'MR-1883', name: 'Transparent Wine Gold Luster', hex: '#6a1828', type: 'Transparent' },
  { code: 'MR-1884', name: 'Transp. Aqua Gold Luster Lt. Purple', hex: '#a173bc', type: 'Transparent' },
  { code: 'MR-1886', name: 'Transparent Smoky Olive Gold Luster', hex: '#6b7a28', type: 'Transparent' },
  { code: 'MR-1887', name: 'Transparent Apricot Topaz Gold Luster', hex: '#a86820', type: 'Transparent' },
  { code: 'MR-1888', name: 'Transparent Root Beer Gold Luster AB', hex: '#d0ae48', type: 'Transparent' },
  { code: 'MR-1889', name: 'Transparent Olive Gold Luster', hex: '#6b7a28', type: 'Transparent' },
  { code: 'MR-1890', name: 'Transparent Emerald Gold Luster AB', hex: '#3e9b57', type: 'Transparent' },
  { code: 'MR-1891', name: 'Transparent Cinnamon Gold Luster AB', hex: '#d0ae48', type: 'Transparent' },
  { code: 'MR-1892', name: 'Transparent Forest Green Gold Luster AB', hex: '#3c6543', type: 'Transparent' },
  { code: 'MR-1893', name: 'Transparent Plum Gold Luster AB', hex: '#743e72', type: 'Transparent' },
  { code: 'MR-1894', name: 'Transparent Mulberry Gold Luster AB', hex: '#d0ae48', type: 'Transparent' },
  { code: 'MR-1895', name: 'Opaque Dark Olive Gold Luster AB', hex: '#60693c', type: 'Opaque' },
  { code: 'MR-1896', name: 'Opaque Blue Gray Gold Luster AB', hex: '#7e8cae', type: 'Opaque' },
  { code: 'MR-1897', name: 'Opaque Golden Olive Gold Luster AB', hex: '#818d48', type: 'Opaque' },
  { code: 'MR-1898', name: 'Opaque Purple Gray Gold Luster AB', hex: '#8d55ae', type: 'Opaque' },
  { code: 'MR-1899', name: 'Opaque Eggplant Gold Luster AB', hex: '#65416a', type: 'Opaque' },
  { code: 'MR-1943', name: 'Opaque Red Luster AB', hex: '#d05555', type: 'Opaque' },
  { code: 'MR-1945', name: 'Opaque Cobalt Luster AB', hex: '#3e66d0', type: 'Opaque' },
  { code: 'MR-1953', name: 'Black AB', hex: '#3c3c3c', type: 'Other' },
  { code: 'MR-1958', name: 'Opaque Metallic Olive Green Iris', hex: '#5a7a2e', type: 'Opaque' },
  { code: 'MR-1959', name: 'Opaque Metallic Blue Iris', hex: '#2870e5', type: 'Opaque' },
  { code: 'MR-1960', name: 'Opaque Metallic Steel Iris', hex: '#667893', type: 'Opaque' },
  { code: 'MR-1962', name: 'Opaque Bronze Gold Luster', hex: '#8a6228', type: 'Opaque' },
  { code: 'MR-1970', name: 'Opaque Metallic Thistle Gold Iris', hex: '#aaa02e', type: 'Opaque' },
  { code: 'MR-1992', name: 'Nickel-Plated Blue AB', hex: '#4169e1', type: 'Galvanized' },
  { code: 'MR-2001', name: 'Opaque Metallic Gunmetal Luster Matte', hex: '#232327', type: 'Matte Metallic' },
  { code: 'MR-2002', name: 'Opaque Metallic Dark Gray Matte AB', hex: '#717171', type: 'Matte Metallic' },
  { code: 'MR-2004', name: 'Opaque Metallic Dark Olive Matte', hex: '#404626', type: 'Matte Metallic' },
  { code: 'MR-2005', name: 'Opaque Metallic Dark Copper Matte AB', hex: '#7b6151', type: 'Matte Metallic' },
  { code: 'MR-2006', name: 'Opaque Metallic Bronze Matte', hex: '#846f4f', type: 'Matte Metallic' },
  { code: 'MR-2006L', name: 'Matte Metallic Lt.Bronze', hex: '#a99a83', type: 'Matte Metallic' },
  { code: 'MR-2007', name: 'Opaque Metallic Blueberry Matte AB', hex: '#6f6f93', type: 'Matte Metallic' },
  { code: 'MR-2008', name: 'Opaque Metallic Sage Iris Matte', hex: '#8ba79c', type: 'Matte Metallic' },
  { code: 'MR-2009', name: 'Opaque Metallic Blue Iris Matte', hex: '#5c83c2', type: 'Matte Metallic' },
  { code: 'MR-2021', name: 'Opaque Cream Matte', hex: '#ece6db', type: 'Matte' },
  { code: 'MR-2022', name: 'Opaque Antique Beige Matte', hex: '#c0b5a0', type: 'Matte' },
  { code: 'MR-2024', name: 'Opaque Rose Matte', hex: '#b46f89', type: 'Matte' },
  { code: 'MR-2028', name: 'Opaque Light Sage Glazed Luster Matte', hex: '#bdc7b9', type: 'Matte' },
  { code: 'MR-2029', name: 'Opaque Turquoise Glazed Luster Matte', hex: '#73b7bf', type: 'Matte' },
  { code: 'MR-2030', name: 'Opaque Denim Gold Luster Matte AB', hex: '#c0ad76', type: 'Matte' },
  { code: 'MR-2031', name: 'Opaque Dark Sage Gold Luster Matte AB', hex: '#74601d', type: 'Matte' },
  { code: 'MR-2032', name: 'Opaque Olive Gold Luster Matte', hex: '#737b4e', type: 'Matte' },
  { code: 'MR-2033', name: 'Opaque Light Olive Gold Luster Matte AB', hex: '#aaaf94', type: 'Matte' },
  { code: 'MR-2034', name: 'Opaque Old Rose Gold Luster Matte', hex: '#bb9099', type: 'Matte' },
  { code: 'MR-2035', name: 'Transparent Bronze Glazed Luster Iris Matte', hex: '#857b62', type: 'Matte' },
  { code: 'MR-2039', name: 'Opaque Dark Violet Glazed Luster Matte', hex: '#432a63', type: 'Matte' },
  { code: 'MR-2040', name: 'Opaque Dark Red Glazed Luster Matte', hex: '#774444', type: 'Matte' },
  { code: 'MR-2065', name: 'Opaque Metallic Charcoal Glazed Luster Matte', hex: '#2d3a43', type: 'Matte Metallic' },
  { code: 'MR-2066', name: 'Opaque Metallic Dark Green Iris Matte', hex: '#294c38', type: 'Matte Metallic' },
  { code: 'MR-2076', name: 'Opaque Red Luster Matte', hex: '#aa5d5d', type: 'Matte' },
  { code: 'MR-2091', name: 'Galvanized Matte Pewter', hex: '#75838e', type: 'Matte' },
  { code: 'MR-2195', name: 'Transparent Color Lined Taupe AB', hex: '#483c32', type: 'Transparent' },
  { code: 'MR-2196', name: 'Transparent Color Lined Topaz AB', hex: '#b57e41', type: 'Transparent' },
  { code: 'MR-2197', name: 'Transparent Color Lined Light Peach AB', hex: '#f5ddcb', type: 'Transparent' },
  { code: 'MR-2199', name: 'Transparent Color Lined Blush AB', hex: '#f2c9d0', type: 'Transparent' },
  { code: 'MR-2200', name: 'Transparent Color Lined Rose Pink Luster', hex: '#c84878', type: 'Transparent' },
  { code: 'MR-2201', name: 'Transparent Color Lined Light Lilac Luster', hex: '#d8bce3', type: 'Transparent' },
  { code: 'MR-2202', name: 'Transparent Color Lined Magenta AB', hex: '#c93e80', type: 'Transparent' },
  { code: 'MR-2205', name: 'Transparent Color Lined Light Blue AB', hex: '#83a9dd', type: 'Transparent' },
  { code: 'MR-2206', name: 'Transparent Color Lined Blue AB', hex: '#4f85d0', type: 'Transparent' },
  { code: 'MR-2207', name: 'Transparent Color Lined Light Aqua Luster', hex: '#7ed8d8', type: 'Transparent' },
  { code: 'MR-2208', name: 'Transparent Color Lined Turquoise Green AB', hex: '#4bd0ae', type: 'Transparent' },
  { code: 'MR-2209', name: 'Transparent Color Lined Pale Violet AB', hex: '#b198d1', type: 'Transparent' },
  { code: 'MR-2210', name: 'Transparent Color Lined Gray AB', hex: '#9b9b9b', type: 'Transparent' },
  { code: 'MR-2212', name: 'Transparent Color Lined Pale Aqua AB', hex: '#91dddd', type: 'Transparent' },
  { code: 'MR-2238', name: 'Transparent Topaz Color Lined Goldenrod Luster AB', hex: '#db8841', type: 'Transparent' },
  { code: 'MR-2240', name: 'Transparent Kelly Green Color Lined Lime Luster', hex: '#3a8a4a', type: 'Transparent' },
  { code: 'MR-2241', name: 'Transparent Color Lined Emerald Green Luster', hex: '#1c8a3a', type: 'Transparent' },
  { code: 'MR-2242', name: 'Transparent Color Lined Emerald Luster AB', hex: '#3e9b57', type: 'Transparent' },
  { code: 'MR-2243', name: 'Transparent Crystal Color Lined Royal Purple Luster', hex: '#e0e8e8', type: 'Transparent' },
  { code: 'MR-2244', name: 'Transparent Color Lined Navy Blue Luster', hex: '#3070c8', type: 'Transparent' },
  { code: 'MR-2248', name: 'Transparent Crystal Color Lined Red Luster AB', hex: '#e4ebeb', type: 'Transparent' },
  { code: 'MR-2249', name: 'Transparent Crystal Color Lined Ruby Luster AB', hex: '#e4ebeb', type: 'Transparent' },
  { code: 'MR-2276', name: 'Transparent Color Lined Steel Luster', hex: '#787880', type: 'Transparent' },
  { code: 'MR-2301', name: 'Matte Metallic Gold Luster', hex: '#b59f5e', type: 'Matte Metallic' },
  { code: 'MR-2355', name: 'Silver-Lined Opal Periwinkle', hex: '#ccccff', type: 'Silver-Lined' },
  { code: 'MR-2359', name: 'Silver-Lined Shell Opal Salmon', hex: '#eba093', type: 'Silver-Lined' },
  { code: 'MR-2405', name: 'Transp. Teal', hex: '#1c8a8a', type: 'Transparent' },
  { code: 'MR-2405F', name: 'Matte Transp. Teal', hex: '#4c8888', type: 'Matte' },
  { code: 'MR-2405FR', name: 'Transparent Matte Caribbean Teal AB', hex: '#669999', type: 'Matte' },
  { code: 'MR-2412', name: 'Transp. Lt. Gray', hex: '#adadad', type: 'Transparent' },
  { code: 'MR-2423', name: 'Dk. Peridot Silver-Lined', hex: '#829949', type: 'Silver-Lined' },
  { code: 'MR-2425', name: 'Silver-Lined Caribbean Teal', hex: '#3e9b9b', type: 'Silver-Lined' },
  { code: 'MR-2429', name: 'Dk. Aqua Silver-Lined', hex: '#4d9494', type: 'Silver-Lined' },
  { code: 'MR-2433', name: 'Lt. Gray Silver-Lined', hex: '#ffffff', type: 'Silver-Lined' },
  { code: 'MR-2439', name: 'Transparent Light Smoky Topaz Glazed Luster', hex: '#fafac9', type: 'Transparent' },
  { code: 'MR-2440', name: 'Transparent Gray Gold Luster AB', hex: '#e2ce8c', type: 'Transparent' },
  { code: 'MR-2441', name: 'Transparent Cinnamon Gold Luster', hex: '#c8a028', type: 'Transparent' },
  { code: 'MR-2442', name: 'Transparent Crystal Ivory Gold Luster', hex: '#e0e8e8', type: 'Transparent' },
  { code: 'MR-2443', name: 'Transparent Light Marine Blue Glazed Luster AB', hex: '#8fb1d0', type: 'Transparent' },
  { code: 'MR-2444', name: 'Transparent Blue Gray Glazed Luster AB', hex: '#8a97b6', type: 'Transparent' },
  { code: 'MR-2445', name: 'Transparent Sea Foam Glazed Luster', hex: '#8cd4c6', type: 'Transparent' },
  { code: 'MR-2456', name: 'Transp. Dk. Topaz AB', hex: '#825f37', type: 'Transparent' },
  { code: 'MR-2457', name: 'Transp. Dk. Aqua AB', hex: '#4d9494', type: 'Transparent' },
  { code: 'MR-2458', name: 'Transp. Teal AB', hex: '#3e9b9b', type: 'Transparent' },
  { code: 'MR-2462', name: 'Transp. Lt. Gray AB', hex: '#b9b9b9', type: 'Transparent' },
  { code: 'MR-2470', name: 'Opaque Turquoise Green Glazed Luster', hex: '#41cda9', type: 'Opaque' },
  { code: 'MR-2549', name: 'Silk Rainbow White', hex: '#f6f6f3', type: 'Silk' },
  { code: 'MR-2550', name: 'Silk Silver-Lined (S/L)', hex: '#ebe5db', type: 'Silver-Lined' },
  { code: 'MR-2565', name: 'Silk Silverline Rainbow', hex: '#ede9e1', type: 'Silver-Lined' },
  { code: 'MR-2593', name: 'Silk Luster Light Tan', hex: '#d5c7ad', type: 'Silk' },
  { code: 'MR-3051', name: 'Transparent Color Lined Sand Dune Mix Luster', hex: '#d4c098', type: 'Transparent' },
  { code: 'MR-3056', name: 'Transparent Color Lined Majestic Mix Luster', hex: '#c0a0d0', type: 'Transparent' },
  { code: 'MR-3470', name: 'Opaque Chocolate AB', hex: '#3e2723', type: 'Opaque' },
  { code: 'MR-3550', name: 'Transparent Saffron Color Lined White Luster AB', hex: '#ebb541', type: 'Transparent' },
  { code: 'MR-366-1', name: 'Transparent Shell Pink Glazed Luster', hex: '#f1a2bf', type: 'Transparent' },
  { code: 'MR-3801', name: 'Pearl-Lined Transparent Beige AB', hex: '#f5f5dc', type: 'Pearlized' },
  { code: 'MR-3805', name: 'Copper Pearl Lined Chartreuse', hex: '#c4cd6a', type: 'Pearlized' },
  { code: 'MR-3815', name: 'Copper Pearl Lined Transparent Aqua Blue', hex: '#b08166', type: 'Pearlized' },
  { code: 'MR-4202F', name: 'Duracoat Galvanized Frost', hex: '#c8ccd0', type: 'Matte' },
  { code: 'MR-4217F', name: 'Duracoat Galvanized Seafoam Frosted', hex: '#94cec2', type: 'Matte' },
  { code: 'MR-4218', name: 'Duracoat Galvanized Dusty Orchid', hex: '#c89fb0', type: 'Duracoat' },
  { code: 'MR-4219', name: 'Duracoat Galvanized Magenta', hex: '#b74178', type: 'Duracoat' },
  { code: 'MR-4220', name: 'Duracoat Galvanized Eggplant', hex: '#593b5d', type: 'Duracoat' },
  { code: 'MR-4221', name: 'Duracoat Galvanized Light Smoky Pewter', hex: '#bad1e2', type: 'Duracoat' },
  { code: 'MR-4221F', name: 'Duracoat Galvanized Light Smoky Pewter Frosted', hex: '#9eb1c0', type: 'Matte' },
  { code: 'MR-4222', name: 'Duracoat Galvanized Pewter', hex: '#8a9ba8', type: 'Duracoat' },
  { code: 'MR-4234', name: 'Duracoat Silver-Lined Transparent Dyed Satin Light Watermelon', hex: '#f19ca5', type: 'Silver-Lined' },
  { code: 'MR-4248', name: 'Duracoat Silver-Lined Transparent Dyed Satin Lilac', hex: '#d4b6e0', type: 'Silver-Lined' },
  { code: 'MR-4249', name: 'Duracoat Silver-Lined Satin Raisin', hex: '#5d2d3f', type: 'Silver-Lined' },
  { code: 'MR-4301', name: 'Luminous Wild Strawberry Pink', hex: '#e6536c', type: 'Luminous' },
  { code: 'MR-4303', name: 'Luminous Plum Crazy', hex: '#7b4c73', type: 'Luminous' },
  { code: 'MR-4460', name: 'Duracoat Opaque Toast', hex: '#b89060', type: 'Opaque' },
  { code: 'MR-4470', name: 'Duracoat Opaque Maroon', hex: '#7a1818', type: 'Opaque' },
  { code: 'MR-4551', name: 'Marea', hex: '#d0a050', type: 'Special' },
  { code: 'MR-4557', name: 'Vitrail Matte', hex: '#7fa1a1', type: 'Matte' },
  { code: 'MR-4558', name: 'Labrador Matte', hex: '#65757d', type: 'Matte' },
  { code: 'MR-4571', name: 'Magic Orchid', hex: '#c878d8', type: 'Special' },
  { code: 'MR-4572', name: 'Magic Blue', hex: '#3070c8', type: 'Special' },
  { code: 'MR-4573', name: 'Magic Wine', hex: '#6a1828', type: 'Special' },
  { code: 'MR-4641', name: 'Duracoat Opaque Dyed French Vanilla', hex: '#f0e8c8', type: 'Opaque' },
  { code: 'MR-4642', name: 'Duracoat Opaque Dyed Terracotta', hex: '#b85a36', type: 'Opaque' },
  { code: 'MR-2023-1', name: 'Opaque Blush Matte', hex: '#e6ccd1', type: 'Matte' },
  { code: 'MR-2025-1', name: 'Opaque Lavender Matte', hex: '#bfadd0', type: 'Matte' },
  { code: 'MR-2026-1', name: 'Opaque Light Gray Matte', hex: '#b5b5b5', type: 'Matte' },
  { code: 'MR-2479-1', name: 'Opaque Smoke Glazed Luster', hex: '#87878a', type: 'Opaque' },
  { code: 'MR-3318-1', name: 'Opaque Light Mint Glazed', hex: '#aae5c8', type: 'Opaque' },
  { code: 'MR-2422(3inRR5/0)', name: 'Dk. Topaz Silver-Lined', hex: '#825f37', type: 'Silver-Lined' },
];
